issues:
  exclude-rules:
    - path: _test.go
      linters:
        - gofmt

run:
  timeout: 5m
  skip-dirs:
    - cmd/maddy-pam-helper

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gofmt
    - ineffassign
