issues:
  exclude-rules:
    - path: _test.go
      linters:
        - gofmt
  exclude-dirs:
    - cmd/maddy-pam-helper

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gofmt
    - ineffassign
