#!/bin/bash
# ──────────────────────────────────────────────────────────────────
# setup_lxc_unprivileged.sh
#
# One-time setup for running LXC containers WITHOUT root/sudo.
# Run this once with:   sudo bash setup_lxc_unprivileged.sh
#
# What it does:
#   1. Installs required packages (lxc, uidmap, dnsmasq, iptables)
#   2. Allocates subordinate UID/GID ranges for the calling user
#   3. Configures ~/.config/lxc/default.conf for unprivileged containers
#   4. Allows the user to create veth pairs on lxcbr0 (lxc-usernet)
#   5. Enables lxc-net service (provides bridge + DHCP)
#   6. Installs a sudoers.d snippet for passwordless host networking
# ──────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Detect the real (non-root) user ─────────────────────────────
if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: This script must be run with sudo."
    echo "Usage: sudo bash $0"
    exit 1
fi

TARGET_USER="${SUDO_USER:-}"
if [ -z "$TARGET_USER" ] || [ "$TARGET_USER" = "root" ]; then
    echo "ERROR: Run this via 'sudo bash $0' from a normal user session."
    exit 1
fi

TARGET_HOME=$(eval echo "~$TARGET_USER")
echo "Setting up unprivileged LXC for user: $TARGET_USER (home: $TARGET_HOME)"
echo "================================================================="

# ── 1. Install required packages ────────────────────────────────
echo ""
echo "[1/6] Installing required packages..."
if command -v pacman &>/dev/null; then
    # Arch Linux
    pacman -S --needed --noconfirm lxc dnsmasq iptables-nft conntrack-tools
elif command -v apt-get &>/dev/null; then
    # Debian / Ubuntu
    apt-get update -qq
    apt-get install -y -qq lxc lxc-templates uidmap dnsmasq-base iptables conntrack
else
    echo "ERROR: Unsupported distro — install lxc, dnsmasq, iptables manually."
    exit 1
fi

# ── 2. Configure subordinate UID/GID ranges ─────────────────────
echo ""
echo "[2/6] Configuring /etc/subuid and /etc/subgid..."

SUB_START=100000
SUB_COUNT=65536

# Add entry if not already present
if ! grep -q "^${TARGET_USER}:" /etc/subuid 2>/dev/null; then
    echo "${TARGET_USER}:${SUB_START}:${SUB_COUNT}" >> /etc/subuid
    echo "  Added ${TARGET_USER}:${SUB_START}:${SUB_COUNT} to /etc/subuid"
else
    echo "  /etc/subuid already has entry for ${TARGET_USER}"
fi

if ! grep -q "^${TARGET_USER}:" /etc/subgid 2>/dev/null; then
    echo "${TARGET_USER}:${SUB_START}:${SUB_COUNT}" >> /etc/subgid
    echo "  Added ${TARGET_USER}:${SUB_START}:${SUB_COUNT} to /etc/subgid"
else
    echo "  /etc/subgid already has entry for ${TARGET_USER}"
fi

# ── 3. Create user LXC config ───────────────────────────────────
echo ""
echo "[3/6] Creating ${TARGET_HOME}/.config/lxc/default.conf..."

LXC_CONF_DIR="${TARGET_HOME}/.config/lxc"
mkdir -p "$LXC_CONF_DIR"

# Read the user's actual subuid/subgid ranges
SUBUID_START=$(grep "^${TARGET_USER}:" /etc/subuid | head -1 | cut -d: -f2)
SUBUID_COUNT=$(grep "^${TARGET_USER}:" /etc/subuid | head -1 | cut -d: -f3)
SUBGID_START=$(grep "^${TARGET_USER}:" /etc/subgid | head -1 | cut -d: -f2)
SUBGID_COUNT=$(grep "^${TARGET_USER}:" /etc/subgid | head -1 | cut -d: -f3)

cat > "${LXC_CONF_DIR}/default.conf" <<EOF
# Unprivileged LXC default configuration
# Generated by setup_lxc_unprivileged.sh

# Network: veth pair attached to lxcbr0 bridge
lxc.net.0.type = veth
lxc.net.0.link = lxcbr0
lxc.net.0.flags = up
lxc.net.0.hwaddr = 00:16:3e:xx:xx:xx

# UID/GID mapping (user namespace)
lxc.idmap = u 0 ${SUBUID_START} ${SUBUID_COUNT}
lxc.idmap = g 0 ${SUBGID_START} ${SUBGID_COUNT}

# Apparmor: allow for unprivileged
lxc.apparmor.profile = unconfined
EOF

chown -R "${TARGET_USER}:${TARGET_USER}" "$LXC_CONF_DIR"
echo "  Created with idmap u 0 ${SUBUID_START} ${SUBUID_COUNT}"
echo "  Created with idmap g 0 ${SUBGID_START} ${SUBGID_COUNT}"

# Also ensure the container storage directory exists
CONTAINER_DIR="${TARGET_HOME}/.local/share/lxc"
mkdir -p "$CONTAINER_DIR"
chown -R "${TARGET_USER}:${TARGET_USER}" "${TARGET_HOME}/.local/share"

# Grant the container's mapped root (UID from subuid range) execute-only
# traversal permission on the user's home directory. Without this, lxc-start
# fails with "Permission denied - Could not access /home/<user>".
# This does NOT grant read or list access — only path traversal (x).
if command -v setfacl &>/dev/null; then
    setfacl -m "u:${SUBUID_START}:x" "${TARGET_HOME}"
    echo "  ACL: granted u:${SUBUID_START}:x on ${TARGET_HOME}"
else
    # Fallback: add o+x (less restrictive but works without ACL support)
    chmod o+x "${TARGET_HOME}"
    echo "  chmod o+x ${TARGET_HOME} (install acl package for a tighter fix)"
fi

# ── 4. Allow veth pairs on lxcbr0 ───────────────────────────────
echo ""
echo "[4/6] Configuring /etc/lxc/lxc-usernet..."

USERNET_ENTRY="${TARGET_USER} veth lxcbr0 10"
if ! grep -q "^${TARGET_USER} " /etc/lxc/lxc-usernet 2>/dev/null; then
    echo "$USERNET_ENTRY" >> /etc/lxc/lxc-usernet
    echo "  Added: ${USERNET_ENTRY}"
else
    echo "  Entry for ${TARGET_USER} already exists in lxc-usernet"
fi

# ── 5. Enable and start lxc-net ─────────────────────────────────
echo ""
echo "[5/6] Enabling lxc-net service..."

# Ensure lxc-net config exists with bridge enabled
if [ -f /etc/default/lxc-net ]; then
    sed -i 's/^USE_LXC_BRIDGE=.*/USE_LXC_BRIDGE="true"/' /etc/default/lxc-net
else
    echo 'USE_LXC_BRIDGE="true"' > /etc/default/lxc-net
fi

systemctl enable lxc-net 2>/dev/null || true
systemctl restart lxc-net 2>/dev/null || true
echo "  lxc-net enabled and started"

# ── 6. Install sudoers snippet for host networking ───────────────
echo ""
echo "[6/6] Installing /etc/sudoers.d/madmail-lxc-test..."

IPTABLES_BIN=$(which iptables 2>/dev/null || echo "/usr/sbin/iptables")
DNSMASQ_BIN=$(which dnsmasq 2>/dev/null || echo "/usr/sbin/dnsmasq")
KILL_BIN=$(which kill 2>/dev/null || echo "/bin/kill")
TEE_BIN=$(which tee 2>/dev/null || echo "/usr/bin/tee")
IP_BIN=$(which ip 2>/dev/null || echo "/usr/sbin/ip")
FUSER_BIN=$(which fuser 2>/dev/null || echo "/usr/bin/fuser")
SYSTEMCTL_BIN=$(which systemctl 2>/dev/null || echo "/usr/bin/systemctl")

# Find sed (could be /bin/sed or /usr/bin/sed)
SED_BIN=$(which sed 2>/dev/null || echo "/usr/bin/sed")

cat > /etc/sudoers.d/madmail-lxc-test <<EOF
# Passwordless sudo for madmail LXC test host-networking commands.
# Installed by: tests/deltachat-test/setup_lxc_unprivileged.sh
# Safe to remove if you no longer run LXC-based tests.

# iptables (NAT masquerade + FORWARD rules for LXC bridge)
${TARGET_USER} ALL=(ALL) NOPASSWD: ${IPTABLES_BIN}

# dnsmasq (test DNS on lxcbr0 for domain-based federation tests)
${TARGET_USER} ALL=(ALL) NOPASSWD: ${DNSMASQ_BIN}

# kill (to stop dnsmasq after tests)
${TARGET_USER} ALL=(ALL) NOPASSWD: ${KILL_BIN}

# fuser (to stop any process on port 53 if needed)
${TARGET_USER} ALL=(ALL) NOPASSWD: ${FUSER_BIN} -k 53/udp
${TARGET_USER} ALL=(ALL) NOPASSWD: ${FUSER_BIN} -k 53/tcp

# ip (to add secondary IPs if needed)
${TARGET_USER} ALL=(ALL) NOPASSWD: ${IP_BIN} addr add *
${TARGET_USER} ALL=(ALL) NOPASSWD: ${IP_BIN} addr del *
${TARGET_USER} ALL=(ALL) NOPASSWD: ${IP_BIN} addr show *

# systemctl (to poke lxc-net if DHCP is stuck)
${TARGET_USER} ALL=(ALL) NOPASSWD: ${SYSTEMCTL_BIN} status lxc-net
${TARGET_USER} ALL=(ALL) NOPASSWD: ${SYSTEMCTL_BIN} restart lxc-net

# tee (append test entries to /etc/hosts)
${TARGET_USER} ALL=(ALL) NOPASSWD: ${TEE_BIN} -a /etc/hosts

# sed (remove test entries from /etc/hosts on cleanup)
${TARGET_USER} ALL=(ALL) NOPASSWD: ${SED_BIN} -i *

# cat (read dnsmasq PID file)
${TARGET_USER} ALL=(ALL) NOPASSWD: /bin/cat /tmp/madmail-test-dnsmasq.pid
${TARGET_USER} ALL=(ALL) NOPASSWD: /usr/bin/cat /tmp/madmail-test-dnsmasq.pid
EOF

chmod 0440 /etc/sudoers.d/madmail-lxc-test
# Validate
if visudo -c -f /etc/sudoers.d/madmail-lxc-test; then
    echo "  Sudoers snippet installed and validated"
else
    echo "  WARNING: sudoers validation failed! Removing file."
    rm -f /etc/sudoers.d/madmail-lxc-test
    exit 1
fi

# ── Summary ──────────────────────────────────────────────────────
echo ""
echo "================================================================="
echo "✓ Setup complete!"
echo ""
echo "You can now run LXC tests WITHOUT sudo:"
echo "  uv run python3 tests/deltachat-test/main.py --lxc --test-7"
echo ""
echo "What changed:"
echo "  • /etc/subuid, /etc/subgid  — UID/GID namespace for ${TARGET_USER}"
echo "  • ${LXC_CONF_DIR}/default.conf — unprivileged container defaults"
echo "  • /etc/lxc/lxc-usernet — veth permission on lxcbr0"
echo "  • lxc-net service — bridge + DHCP enabled"
echo "  • /etc/sudoers.d/madmail-lxc-test — passwordless networking cmds"
echo ""
echo "Containers will be stored in: ${CONTAINER_DIR}/"
echo "To undo: sudo rm /etc/sudoers.d/madmail-lxc-test"
echo "================================================================="
